name = "HierarchicMemeticStrategy"
uuid = "e8a7ceb1-99d9-4ed8-9423-a05c7ce6343c"
authors = ["Wiktor Cie≈õlikiewicz"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ConcurrentCollections = "5060bff5-0b44-40c5-b522-fcd3ca5cecdd"
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1.10"
ConcurrentCollections = "0.1.1"
Colors = "0.13.1"
DefaultApplication = "1.1.0" 
Distributions = "0.25.123"
Evolutionary = "0.11.1"
LineSearches = "7.5.1"
Optim = "1.13.3"
PlotlyJS = "0.18.17"
Statistics = "1.10.0"
LinearAlgebra = "1.10"
Random = "1.10"
UUIDs = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
